DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE IF NOT EXISTS messages (
	id SERIAL NOT NULL,
	title VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	created_at TIMESTAMP,
	updated_at TIMESTAMP
);